config/routes.rb
Rails.application.routes.draw do
  root 'homepage#index'
  get '/homepage/help', to: 'homepage#help'
  
  resources:imaps
  resources:adresses
end

app/models/adress.rb
class Adress < ApplicationRecord
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true
    validates :servsmtp, presence: true
    validates :port, presence: true, numericality: { only_integer: true }
    validates :authentication, presence: true
    validates :starttls, presence: true
    validates :domain, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/imap.rb
class Imap < ApplicationRecord
    validates :label, presence: true 
    validates :login, presence: true, uniqueness: true
    validates :password, presence: true
    validates :servimap, presence: true
end

app/controllers/adresses_controller.rb
require 'net/imap'

class AdressesController < ApplicationController
  def index
    @adresses = Adress.order(:isValid).reverse
    @imaps = Imap.all
    @adresses.each do |adresse|
      #met à jour "l'age" des adresses
      if adresse.nbHours == 24
        adresse.update(age: adresse.age + 1)
        adresse.update(nbHours: 0)
      end
      #augmente de 30% la limite de mails par heure en fonction de l'ancienneté (20 par defaut au premier jour)
      if adresse.age == 0
        adresse.update(hourlyLimit: 20)
      else
        adresse.update(hourlyLimit: 20)
        for i in 1..adresse.age
          adresse.update(hourlyLimit: adresse.hourlyLimit + (adresse.hourlyLimit * 0.3).round(0).to_i)
        end
      end
    end
    CheckValidityJob.perform_later()
  end

  def show
    @adress = Adress.find(params[:id])
    @activeImaps = Imap.where("isValid = true").where("isActive = 'active'")

    if @adress.mailCount == nil
      @adress.update(mailCount: 0)
    end
    SendMailJob.perform_later(params[:id])
  end

  def new
    @adress = Adress.new
  end

  def create
    @adress = Adress.new(adress_params)

    if @adress.save
      @adress.update(beginDate: Date.today)
      begin
        smtp = Net::SMTP.start(adress.servsmtp, adress.port, adress.domain, adress.email, adress.password)
        @adress.update!(isValid: true)
      rescue
        #reste sur la meme page si il y a eu une erreur de connexion au serveur mail
        @adress.update!(isValid: false)
        redirect_to edit_adress_path(@adress)
      ensure
        if smtp != nil
          smtp.finish
        end
      end
      if @adress.isValid
        redirect_to '/adresses'
      end
    else
      render :new #renvoie a new si il y a eu un problème
    end
  end

  def edit
    @adress = Adress.find(params[:id])
    @activeImaps = Imap.where("isValid = true").where("isActive = 'active'")
  end

  def update
    @adress = Adress.find(params[:id])

    if @adress.update(adress_params)
      begin
        smtp = Net::SMTP.start(adress.servsmtp, adress.port, adress.domain, adress.email, adress.password)
        @adress.update!(isValid: true)
      rescue
        #reste sur la meme page si il y a eu une erreur de connexion au serveur mail
        @adress.update!(isValid: false)
        redirect_to edit_adress_path(@adress)
      ensure
        if smtp != nil
          smtp.finish
        end
      end
      if @adress.isValid
        redirect_to '/adresses'
      end
    else
      render :edit #renvoie a edit si il y a eu un problème
    end
  end

  def destroy
    @adress = Adress.find(params[:id])
    @adress.destroy
    redirect_to '/adresses'
  end

  private
    def adress_params
      params.require(:adress).permit(:servsmtp, :email, :password, :mailCount, :beginDate, :age, :port, :starttls, :authentication, :isValid, :domain)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
    def index
    end

    def help
    end
end

app/controllers/imaps_controller.rb
require 'net/imap'
require 'resolv-replace'

class ImapsController < ApplicationController

  def index
    @imaps = Imap.all
  end
  
  def show
    @imap = Imap.find(params[:id])
    @imapAccess = nil
    @adresses = Adress.all
  end

  def new
    @imap = Imap.new
  end

  def create
    @imap = Imap.new(imap_params)

    if @imap.save
      #test si l'adresse créée est valide, renvoie sur le menu d'édition si elle ne l'est pas
      begin
        imapAccess = Net::IMAP.new(@imap.servimap, 993, true)
        imapAccess.login(@imap.login, @imap.password)
        @imap.update!(isValid: true)
      rescue
        @imap.update!(isValid: false)
        redirect_to edit_imap_path(@imap)
      ensure
        if imapAccess != nil
          imapAccess.disconnect
        end
      end
      if @imap.isValid
        redirect_to '/adresses'
      end
    else
      render :new #renvoie a new si il y a eu un problème
    end
  end

  def edit
    @imap = Imap.find(params[:id])
  end

  def update
    @imap = Imap.find(params[:id])

    if @imap.update(imap_params)
      #test si l'adresse éditée est valide,  renvoie sur le menu d'édition si elle ne l'est pas
      begin
        imapAccess = Net::IMAP.new(@imap.servimap, 993, true)
        imapAccess.login(@imap.login, @imap.password)
        @imap.update!(isValid: true)
      rescue
        @imap.update!(isValid: false)
        redirect_to edit_imap_path(@imap)
      ensure
        if imapAccess != nil
          imapAccess.disconnect
        end
      end
      if @imap.isValid
        redirect_to '/adresses'
      end
    else
      render :edit #renvoie a edit si il y a eu un problème
    end
  end

  def destroy
    @imap = Imap.find(params[:id])
    @imap.destroy
    redirect_to '/adresses'
  end

  private
    def imap_params
      params.require(:imap).permit(:label, :servimap, :servsmtp,:login, :password, :isActive, :isValid)
    end
end

app/helpers/adresses_helper.rb
module AdressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imaps_helper.rb
module ImapsHelper
end

app/views/adresses/edit.html.erb
<%=render "/partials/css"%>
<%=render "/partials/navbar"%>
<body>
<%if !@adress.isValid%>
    <div class="container warning-message">
        <p><strong class=warning>Connection au serveur mail impossible, cela peut être du à la connection, ou au mauvais renseignement des données demandées ci-dessous</strong></p>
        <p><strong class=warning>L'adresse est donc comptée comme invalide et ne recevra donc aucun mail tant qu'elle ne sera pas corrigée</strong></p>
    </div>
<%end%>

<div class="container formAddress">
<h1>Editer l'adresse</h1>
<%= render "/adresses/form", adress: @adress%>
<%=button_to "supprimer", adress_path(@adress),
    method: :delete,
    data: { confirm: "Êtes-vous sûr de vouloir supprimer?" }, 
    class:"btn btn-outline-danger",
    style: "margin-top: 30px"%>
</div>

<div class="container addressStats">
  <strong>-Cette adresse a déja envoyée <%=@adress.mailCount.to_s%> mails</strong><br>
  <br>
  <%if @adress.sendHour != nil and @adress.nextHour != nil %>
    <%nextHour = Time.now.advance(hours: 1).hour%>
    <%if nextHour == 24
        nextHour.to_s = "00"
      end%>
    <strong>-Cette adresse a distribué ses mails de <%=Time.now.hour%>h, elle en renverra à <%=nextHour%>h si cette page est ouverte</strong>
    <br>
  <%end%>
  <br>
  <strong>-Cette adresse envoie <%=@adress.hourlyLimit%> mails par heure par adresse réceptrice active, soit <%=@adress.hourlyLimit * @activeImaps.length%> mails par heure</strong>
</div>
<%= button_to 'Retour', 'javascript:history.back()', method: :get, class: "btn btn-outline-dark retour", style: "margin-top: 20px"%>
</body>
<%=render "/partials/footer"%>

app/views/adresses/index.html.erb
<%=render "/partials/css"%>
<%=render "/partials/navbar"%>

<!--affiche les adresses à chauffer-->
<body>
<div class="row">
<div class="container listGroupe1 list-group col mr-3" style="margin-top:5%; margin-left:15%">
<h1>Liste des adresses à chauffer</h1>
<h5>Cliquer sur une des adresses suivantes déclanchera directement le processus de warm-up, les informations de la session d'envoies pourront être consultées sur le terminal du serveur</h5>
  <% @adresses.each do |adresse| %>
  <%adresse.mailCount = 0 if adresse.mailCount == nil%>
  <div class="d-flex">
      <%= link_to "#{adresse.email} (#{adresse.mailCount} mails)", adresse, class: "list-group-item list-group-item-action list-group-item-primary max-w600 #{"list-group-item-danger max-w600" unless adresse.isValid}"%>
      <%=button_to "edit", edit_adress_path(adresse), method: :get, style: "border-radius : 1px; padding: 10px; border-color: rgb(188, 199, 216)", class: "btn btn-outline-secondary"%>
  </div>
  <% end %>
<%= button_to "Nouvelle adresse à chauffer", new_adress_path, method: :get, style: "margin-top: 32px", class:"btn btn-outline-primary"%>
</div>
<!--affiche les adresses réceptrices en 3 groupes (active, inactive, invalide)-->
<div class="container listGroupe2  col" style="margin-top:5%; margin-right:15%">
  <h1>Liste des adresses réceptrices</h1>

  <%active = []
    inactive = []
    invalid = []

    @imaps.each do |imap|
      if !imap.isValid
        invalid.push(imap)
        next
      end
      if imap.isActive == "active"
        active.push(imap)
        next
      end
      if imap.isActive == "inactive"
        inactive.push(imap)
        next
      end
    end
  %>

  <div class="list-group">
    <% active.each do |imap| %>
        <%= link_to imap.login, edit_imap_path(imap), class: "list-group-item list-group-item-action list-group-item-primary"%>
    <% end %>
    <% inactive.each do |imap| %>
        <%= link_to imap.login, edit_imap_path(imap), class: "list-group-item list-group-item-action list-group-item-warning"%>
    <% end %>
    <% invalid.each do |imap| %>
        <%= link_to imap.login, edit_imap_path(imap), class: "list-group-item list-group-item-action list-group-item-danger"%>
    <% end %>
  </div>
  <%= button_to "Nouvelle adresse réceptrice", new_imap_path, method: :get, class:"btn btn-outline-primary", style: "margin-top: 32px" %><br>
</div>
</div>

</body>

<script>
    //actualise la page toutes les 10s
    window.setInterval('refresh()', 10000);

    function refresh() {
        window .location.reload();
    }
</script>

app/views/adresses/new.html.erb
<%=render "/partials/css"%>
<%=render "/partials/navbar"%>
<body>
<div class="container formAddress">
    <h1>Nouvelle adresse à chauffer</h1>
    <%=render '/adresses/form'%>
</div>
<%= button_to 'Retour', 'javascript:history.back()', method: :get, class: "btn btn-outline-dark retour", style:"margin-top: 20px"%>
</body>

app/views/adresses/show.html.erb
<%=render "/partials/css"%>
<%=render "/partials/navbar"%>

<body>

<%if !@adress.isValid%>
    <div class="container warning-message">
        <p><strong class=warning>Connection au serveur mail impossible, cela peut être du à la connection, ou au mauvais renseignement des données demandées ci-dessous</strong></p>
        <p><strong class=warning>L'adresse est donc comptée comme invalide et n'enverra donc aucun mail tant qu'elle ne sera pas corrigée</strong></p>
    </div>
<%end%>

<div class="container addressShow">
  <h1>Informations :</h1>

  <ul class="list-group">
  <li class="list-group-item"><%= @adress.servsmtp %></li>
  <li class="list-group-item"><%= @adress.email %></li>
  <li class="list-group-item"><%= @adress.password %></li>

  </ul>

  <%= button_to "Edit", edit_adress_path(@adress), method: :get, class: "btn btn-outline-primary", style:"margin-top: 10px"%>
  <%= button_to "Supprimer", adress_path(@adress),
                    method: :delete,
                    data: { confirm: "Are you sure?" },
                    class: "btn btn-outline-danger",
                    style: "margin-top: 35px"%>
</div>

<div class="container addressStats">
  <strong>-Cette adresse a déja envoyée <%=@adress.mailCount.to_s%> mails</strong><br>
  <br>
  <%if @adress.sendHour != nil and @adress.nextHour != nil %>
    <%nextHour = Time.now.advance(hours: 1).hour%>
    <%if nextHour == 24
        nextHour.to_s = "00"
      end%>
    <strong>-Cette adresse a distribué ses mails de <%=Time.now.hour%>h, elle en renverra à <%=nextHour%>h si cette page est ouverte</strong>
    <br>
  <%end%>
  <br>
  <strong>-Cette adresse envoie <%=@adress.hourlyLimit%> mails par heure par adresse réceptrice active, soit <%=@adress.hourlyLimit * @activeImaps.length%> mails par heure</strong>
</div>

<div class="container listGroup3">
<h3>Liste des adresses réceptrices actives:</h3>
<div class="list-group">
  <% @activeImaps.each do |imap| %>
  <div class="d-flex">
      <%= link_to imap.login, edit_imap_path(imap), class: "list-group-item list-group-item-action list-group-item-primary #{"list-group-item-secondary" if imap.isActive == "inactive"} #{'list-group-item-danger' unless imap.isValid}"%>
  </div>    
  <% end %>
</div>
</div>

<%= button_to "Retour", 'javascript:history.back()', method: :get, class:"btn btn-outline-dark mr-top2" %>
</body>

<script>
    //actualise la page toutes les minutes
    window.setInterval('refresh()', 60000);

    function refresh() {
        window .location.reload();
    }
</script>

app/views/homepage/help.erb
<%=render "/partials/css"%>
<%=render "/partials/navbar"%>
<body>
<body>
    <h1>Informations</h1>
    <h3>jules.pascualramon.sio2020@gmail.com</h3>
</body>
</body>

app/views/homepage/index.html.erb
<%=render "/partials/css"%>
<%=render "/partials/navbar"%>
<body>
<div>
<h1>HOMEPAGE</h1>
<br>
<label><ins>Problème : </ins></label><br>
<img src="assets/spam.png" alt="illustration">
<br><br>
<hr style="width:35%; margin:auto;">
<label><ins>Solution : </ins></label><br>
<img src="assets/warmup.png" alt="illustration">
<br><br>
<hr style="width:35%; margin:auto">
<label><ins>Résultat : </ins></label><br>
<img src="assets/reputation.png" alt="illustration">
<br>
<hr style="width:35%; margin:auto">
<br>
<%= button_to 'informations', '/homepage/help', method: :get , class: "btn btn-outline-dark mt-1"%><br>
<%= button_to 'liste des adresses à chauffer', adresses_path, method: :get , class: "btn btn-outline-dark mb-3"%>
</div>
</body>

app/views/imaps/edit.html.erb
<%=render "/partials/css"%>
<%=render "/partials/navbar"%>
<style>
.delete_button{
    background-color: red;
    color: white;
}

#inbox{
    color:green
}
#spam{
    color:orange
}
#important{
    color:blue
}
</style>
<body>

<%if !@imap.isValid%>
    <div class="container warning-message">
        <p><strong class=warning>Connection au serveur mail impossible, cela peut être du à la connection, ou au mauvais renseignement des données demandées ci-dessous</strong></p>
        <p><strong class=warning>L'adresse est donc comptée comme invalide et ne recevra donc aucun mail tant qu'elle ne sera pas corrigée</strong></p>
    </div>
<%end%>


<div class="container formImap">
<h1>Editer l'adresse réceptrice</h1>

<%= render "form", imap: @imap%>
<%= button_to "Supprimer l'adresse", imap_path(@imap),
                  method: :delete,
                  data: { confirm: "Êtes-vous sûr de vouloir supprimer?" }, 
                  class:"btn btn-outline-danger",
                  style: "margin-top: 35px"%><br><br>
</div>

<!--met à 0 si les compteurs sont nul-->
<%
if @imap.inboxCount == nil
    @imap.update!(inboxCount: 0)
end
if @imap.spamCount == nil
    @imap.update!(spamCount: 0)
end
if @imap.importantCount == nil
    @imap.update!(importantCount: 0)
end
%>

<!--affiche les stats en %-->
<%if @imap.importantCount != 0%>
    <div class="container imapStats">
    <strong id="inbox"><%=(@imap.inboxCount.to_f * 100 / @imap.importantCount.to_f).round(0).to_s%>% (<%=@imap.inboxCount.to_s%>) des mails importants sont arrivés dans la boite de réception</strong><br>
    <strong id="spam"><%=(@imap.spamCount.to_f * 100 / @imap.importantCount.to_f).round(0).to_s%>% (<%=@imap.spamCount.to_s%>) des mails importants sont arrivés dans les spams</strong><br>
    <strong id="important"><%=(@imap.importantCount.to_f * 100 / @imap.importantCount.to_f).round(0).to_s%>% (<%=@imap.importantCount.to_s%>) des mails à trier ont été déplacés dans le dossier important</strong><br>
    </div><br>
<%else%>
    <p style="margin-top: 20px"><strong>Cette adresse n'a pas encore traité de mail</strong></p>
<%end%>
<%= button_to 'Retour', 'javascript:history.back()', method: :get, class: "btn btn-outline-dark retour"%>
</body>

app/views/imaps/index.html.erb
<%=render "/partials/css"%>
<%=render "/partials/navbar"%>

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<body>
<h1>Liste des adresses IMAP</h1>
<div class="container col-sm-3 list-group">
  <% @imaps.each do |imap| %>
      <%= link_to imap.login, imap, 
          target: :same_as_the_view,
          class: "list-group-item list-group-item-ation #{"list-group-item-danger" if imap.isActive == "inactive"}"%>
  <% end %>
</div>
<%= link_to "Nouvelle adresse IMAP", new_imap_path %><br>
<%= link_to "Retour", '/' %>
</body>

app/views/imaps/show.html.erb
<%=render "/partials/css"%>
<%=render "/partials/navbar"%>
<style>
#inbox{
    color:green
}
#spam{
    color:orange
}
#important{
    color:blue
}
</style>

<!--CETTE PAGE EST INUTILE ET EST DEVENUE INACCESSIBLE SUR LE SITE--->
<!--CERTAINES DE SES FONCTIONALITES ONT ETE DEPLACEE SUR LA PAGE IMAP EDIT--->

<!--affiche toutes les infos de l'adresse IMAP-->
<body>
<h1>Informations :</h1>
<div class="container col-sm-2">
<ul class="list-group">
<li class="list-group-item">boite mail : <%= @imap.label %></li>
<li class="list-group-item">login : <%= @imap.login%></li>
<li class="list-group-item">mot de passe : <%= @imap.password%></li>
</ul>
</div>
<br>

<h2>Statistiques de l'adresse <%=@imap.login%>:</h2><br>

<!--affiche les stats en %-->
<%if @imap.importantCount != 0%>
    <div>
    <strong id="inbox"><%=(@imap.inboxCount.to_f * 100 / @imap.importantCount.to_f).round(0).to_s%>% des mails importants sont arrivés dans la boite de réception</strong><br>
    <strong id="spam"><%=(@imap.spamCount.to_f * 100 / @imap.importantCount.to_f).round(0).to_s%>% des mails importants sont arrivés dans les spams</strong><br>
    </div><br>
<%end%>

<button id=button1 class="btn btn-dark" onclick="showMore()">Voir plus</button><br><br>

<div id="showMore">
<!-- <strong>Cette adresse compte <%=@imap.repCount.to_s%> réponses envoyées</strong><br> -->
<strong id="inbox"><%=@imap.inboxCount.to_s%> mails à trier sont arrivés dans la boite de récption</strong><br>
<strong id="spam"><%=@imap.spamCount.to_s%> mails à trier sont arrivés dans spam</strong><br>
<strong id="important"><%=@imap.importantCount.to_s%> mails à trier ont été déplacés dans important</strong><br>
<br>
</div>
</body>

<!--définit les dossier IMPORTANT et SPAM pour les différentes boites mails, connecte en SMTP les boites mails autre que Gmail-->
<%
spamFolder = ""
importantFolder = ""
case @imap.label
    when "Gmail"
        spamFolder = "[#{@imap.label}]/Spam"
        importantFolder = "Starred"

        #paramètres SMTP pour action mailer
        delivery_options = { port: 587,
          user_name: @imap.login,
          password: @imap.password,
          address: 'smtp.gmail.com',
          enable_starttls_auto: true,
          authentication: 'plain' }

        #serveur IMAP
        servimap = 'imap.gmail.com'

    when "Yahoo"
        spamFolder = "Bulk Mail"
        importantFolder = "Important"

        delivery_options = { port: 587,
          user_name: @imap.login,
          password: @imap.password,
          address: 'smtp.mail.yahoo.com',
          enable_starttls_auto: false,
          authentication: 'plain' }

        servimap = 'imap.mail.yahoo.com'

    when "AOL"
        spamFolder = "Bulk Mail"
        importantFolder = "Important"

        delivery_options = { port: 587,
          user_name: @imap.login,
          password: @imap.password,
          address: 'smtp.aol.com',
          enable_starttls_auto: false,
          authentication: 'plain' }

        servimap = 'imap.aol.com'

    when "Outlook"
        spamFolder = "Junk"
        importantFolder = "Important"

        delivery_options = { port: 587,
          user_name: @imap.login,
          password: @imap.password,
          address: 'smtp.office365.com',
          enable_starttls_auto: true,
          authentication: 'login' }

        servimap = 'outlook.office365.com'

    when "Free"
        spamFolder = "Junk"
        importantFolder = "Important"

        #paramètres SMTP pour action mailer
        delivery_options = { port: 587,
          user_name: @imap.login,
          password: @imap.password,
          address: 'smtp.free.fr',
          enable_starttls_auto: true,
          authentication: 'plain' }
    else
        spamFolder = "[#{imap.label}]/Spam"
        importantFolder = "Important"
    end
%>

<!--Connection en IMAP-->
<%@imapAccess = Net::IMAP.new(servimap, 993, true)
  @imapAccess.login(@imap.login, @imap.password)%>

<%begin%>
<!--Lis et affiche les mails du dossier IMPORTANT-->
<div class="col-sm-5 container">
<ul class="list-group">
<%@imapAccess.select("[#{@imap.label}]/#{importantFolder}")%>
<%@imapAccess.search(["SINCE", "#{rand(1..30)}-May-#{rand(2010..2021)}"]).each do |message|%>
    <%if @imapAccess.fetch(message, "ENVELOPE") != nil%>
        <%important = @imapAccess.fetch(message, "ENVELOPE")[0].attr["ENVELOPE"]%>
        <%if important.subject == nil%>
            <li class="list-group-item list-group-item-primary"><%=" IMPORTANT : " + important.from[0].mailbox + " : No subject"%></li>
        <%else%>
            <li class="list-group-item list-group-item-primary"><%=" IMPORTANT : " + important.from[0].mailbox + " : " + important.subject%></li>
        <%end%>
    <%else%>
        <li id=erreur class="list-group-item list-group-item-danger"><%=" ERREUR : Il y a eu un problème"%></li>
    <%end%>
<%end%>

<!--parcours de la boite de récéption et affichage des mails-->
<%@imapAccess.select('INBOX')%>
<%@imapAccess.search(["SINCE", "#{rand(1..30)}-May-#{rand(2010..2021)}"]).each do |message|%>
    <%unless @imapAccess.fetch(message, "ENVELOPE") == nil%>
        <%envelope = @imapAccess.fetch(message, "ENVELOPE")[0].attr["ENVELOPE"]%>
        <%if envelope.subject == nil%>
            <li class="list-group-item list-group-item-secondary"><%=" INBOX : " + envelope.from[0].mailbox + " : No subject"%></li>
        <%else%>
            <li class="list-group-item list-group-item-secondary"><%=" INBOX : " + envelope.from[0].mailbox + " : " + envelope.subject%></li>
        <%end%>
    <%else%>
        <li class="list-group-item list-group-item-danger"><%=" ERREUR : Il y a eu un problème"%></li>
    <%end%>
<%end%>

<!--parcours des spams et affichage des mails-->
<%@imapAccess.select(spamFolder)%>
<%@imapAccess.search(["SINCE", "#{rand(1..30)}-May-#{rand(2010..2021)}"]).each do |message|%>
    <%unless @imapAccess.fetch(message, "ENVELOPE") == nil%>
        <%spam = @imapAccess.fetch(message, "ENVELOPE")[0].attr["ENVELOPE"]%>
        <%if spam.subject == nil%>
            <li class="list-group-item list-group-item-warning"><%=" IN SPAM : " + spam.from[0].mailbox + " : No subject"%></li>
        <%else%>
            <li class="list-group-item list-group-item-warning"><%=" IN SPAM : " + spam.from[0].mailbox + " : " + spam.subject%></li>
        <%end%>
    <%else%>
        <li id=erreur class="list-group-item list-group-item-danger"><%=" ERREUR : Il y a eu un problème"%></li>
    <%end%>
<%end%>
</ul>
</div>
<body>
<br>
<!--Liens vers Edit, Destroy, Retour-->
<%= link_to "Edit", edit_imap_path(@imap) %><br>
<%= link_to "Destroy", imap_path(@imap),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %><br><br>
<%= link_to "Retour", '/imaps' %>
<br><br>
<button id=button2 class="btn btn-dark" onclick="showhide()">Voir les dossiers</button>

<!--Affiche la liste des dossiers de la boite mail-->
<br><br><p id=list><%=@imapAccess.list('', '*')%></p><br>
</body>

<%ensure%>
<%@imapAccess.disconnect%>
<%end%>

<script>
    document.getElementById("list").style.display = "none";
    document.getElementById("showMore").style.display = "none";
    
    //actualise la page toutes les 2min
    window.setInterval('refresh()', 120000);

    function refresh() {
        window .location.reload();
    }

    //affiche ou cache les listes
    function showhide()
    {
         var list = document.getElementById("list");
         var button = document.getElementById("button2")


        if (list.style.display == "none") {
            list.style.display = "block";
            button.innerHTML = "Masquer les dossiers"
        } else {
            list.style.display = "none";
            button.innerHTML = "Voir les dossiers"
        }
    }

    function showMore()
    {
         var list = document.getElementById("showMore");
         var button = document.getElementById("button1")

        if (list.style.display == "none") {
            list.style.display = "block";
            button.innerHTML = "Voir moins"
        } else {
            list.style.display = "none";
            button.innerHTML = "Voir plus"
        }
    }
</script>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark"  style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#">IP Warm-Up</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= button_to 'Home', '/', method: :get, class: "btn btn-outline-light me-2 btn-navbar" %>
      </li>
      <li class="nav-item">
        <%= button_to 'Warm-Up', adresses_path, method: :get, class: "btn btn-outline-light me-2 btn-navbar" %>
      </li>
      <li class="nav-item">
        <%= button_to "Statistiques", '/homepage/help', method: :get, class: "btn btn-outline-light me-2 btn-navbar"%>
      </li>
    </ul>
  </div>
</nav>